### ISSUE TITLE
test_iex.ex is not installed

### ISSUE THREAD

**Issue by jeremyjh** [scottming/vscode-elixir-test-in-iex#7]
The extension did not install this file, but requires it. I don't see it in the extension archive or this repository, where is it supposed to find it?

** (Code.LoadError) could not load /Users/jeremy/.test_iex/lib/test_iex.ex. Reason: enoent
    (elixir 1.14.3) lib/code.ex:1826: Code.find_file!/2

**Comment by scottming** [comment]
Here: https://github.com/scottming/vscode-elixir-test-in-iex#requirements
And I think I should use `git submodule`; after this busy period, I will change to this.

**Comment by jeremyjh** [comment]
@scottming yeah sorry I missed that. I even searched the repo on that string. But yes, it would be nice if you include it with the extension similar to how elixir_ls does.
