### ISSUE TITLE
Not working with Elixir 1.15

### ISSUE THREAD

**Issue by zwippie** [scottming/vscode-elixir-test-in-iex#9]
Since Elixir 1.15, `iex` does not support the `--no-pry` option any more. To be more specific; [it's now the default](https://elixirforum.com/t/iex-no-pry-not-working-in-elixir-1-15/56887/3).

Because of that, the elixir-test-in-iex plugin now fails all commands with the message: _No file named --no-pry_ when using Elixir 1.15.

I don't know if just removing the option [here](https://github.com/scottming/vscode-elixir-test-in-iex/blob/master/src/helpers/validations.ts#L30) would cause trouble for older Elixir versions. If so, some sort of version detection would be required.

**Comment by scottming** [comment]
Thanks for the reach out, and yes, I know this problem.

I'm working on supporting Elixir 1.15 with Lexical LS: https://github.com/lexical-lsp/lexical/issues/243

And any ideas of version detection, as I know: 

```elixir
~/C/lexical support-elixir-1.15 = !1 ❯ time elixir -e "IO.puts(System.version())"            
1.14.5
elixir -e "IO.puts(System.version())"  0.21s user 0.32s system 130% cpu 0.410 total
```

is too slow.

**Comment by zwippie** [comment]
Good to know it's on your radar! :)

For simplicity, maybe just add a warning in the README for Elixir <1.15 users to stick to an older version of this plugin

 (TBH I haven't tried the plugin with Elixir 1.14 without the `--no-pry` option, maybe it works just fine)

**Comment by scottming** [comment]
> For simplicity, maybe just add a warning in the README for Elixir <1.15 users to stick to an older version of this plugin

Thanks, added.

> (TBH I haven't tried the plugin with Elixir 1.14 without the --no-pry option, maybe it works just fine)

It will, but the `pry` is annoying, especially when you using the `dbg`

**Comment by scottming** [comment]
Hi, @zwippie that pr should work for both 1.15 and below versoin , and `asdf current elixir` is fast.

But I have to find time to write tests, then we can release a new version.
